# Whole Pipeline


In [1]:
import os
import cv2
import numpy
from glob import glob



%load_ext autoreload
%autoreload 2


from va_functions.bootstrap import initialize_visual_odometry

In [2]:
# Data loader
from va_functions.data_loader import load_dataset

# Part I
An initialization module that extracts an initial set of 2D ↔ 3D correspondences from the first frames of the sequence and bootstraps the initial camera poses and landmarks.

In [3]:
dataset_id = 0 # 0: KTTI, 1: Malaga, 2: Parking
#I somehow don't manage to load tha malaga images
left_images, right_images, camera_intrinsics = load_dataset(dataset_id)

print("Loaded", len(left_images), "left images")


Loaded 2761 left images


In [4]:
print("left_images:", left_images[:3])

left_images: ['/home/simon/ETH/VAMR/va_final_prj/data/provided_data/kitti/05/image_0/000000.png', '/home/simon/ETH/VAMR/va_final_prj/data/provided_data/kitti/05/image_0/000001.png', '/home/simon/ETH/VAMR/va_final_prj/data/provided_data/kitti/05/image_0/000002.png']


In [5]:
# Extract initial set of 2D <-> 3D correspondences and bootstrap the Initial Camera Pose and landmarks

# Exampke usage:



initialization_frames = [0, 1, 2, 3] #Specify here over which frames we try to track the first corners
plot_tracked_points = True


vo_initialization_dict = initialize_visual_odometry(frames=initialization_frames, all_images_path=left_images,
                                                    K=camera_intrinsics, plot_tracked_points=plot_tracked_points, dataset_id=dataset_id)

R_Wi = vo_initialization_dict['R_Wi']
W_t_Wi = vo_initialization_dict['W_t_Wi']
matched_keypoints = vo_initialization_dict['matched_keypoints']
W_landmarks_of_keypoints = vo_initialization_dict['W_landmarks_of_keypoints']



print("R_Wi\n", R_Wi)
print("W_t_Wi\n", W_t_Wi)
length_w_t_Wi = numpy.linalg.norm(W_t_Wi)
print("||W_t_Wi|| =", length_w_t_Wi, "should be ~1")






Frame 1: Tracked 239 / 241 points.
from previous num fratures: 241  to current num features: 239
Frame 2: Tracked 239 / 239 points.
from previous num fratures: 239  to current num features: 239
Frame 3: Tracked 239 / 239 points.
from previous num fratures: 239  to current num features: 239
Recovered Pose: 214 / 239 inliers after R,t estimation.
R_Wi
 [[ 0.99981291 -0.00880532 -0.01722223]
 [ 0.00872391  0.99995044 -0.00479646]
 [ 0.01726361  0.00464532  0.99984018]]
W_t_Wi
 [[ 0.14603364]
 [-0.02862987]
 [ 0.98886526]]
||W_t_Wi|| = 1.0 should be ~1


# Part II
A continuous VO module that processes each frame Ii, estimates the current pose of the camera T i W C using the existing set of landmarks, and regularly triangulates new landmarks.

In [6]:
#Associate keypoints in the current frame to previously triangulated landmarks

In [7]:
#Based on this, estimate the current camera pose

In [8]:
# Regularly triangulate new landmarks using keypoints not associated to previously triangulated landmarks