# Whole Pipeline


In [219]:
import os
import cv2
import numpy
from glob import glob



%load_ext autoreload
%autoreload 2


from va_functions.bootstrap import initialize_visual_odometry

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [220]:
# Data loader
from va_functions.data_loader import load_dataset

# Part I
An initialization module that extracts an initial set of 2D ↔ 3D correspondences from the first frames of the sequence and bootstraps the initial camera poses and landmarks.

In [221]:
dataset_id = 2 # This shoudl be dataset parking, i think the function descriptioj is wrong
left_images, right_images, camera_intrinsics = load_dataset(dataset_id)

In [222]:
print("left_images:", left_images[:3])

left_images: ['/home/simon/ETH/VAMR/va_final_prj/data/provided_data/parking/images/img_00000.png', '/home/simon/ETH/VAMR/va_final_prj/data/provided_data/parking/images/img_00001.png', '/home/simon/ETH/VAMR/va_final_prj/data/provided_data/parking/images/img_00002.png']


In [223]:
# Extract initial set of 2D <-> 3D correspondences and bootstrap the Initial Camera Pose and landmarks

# Exampke usage:



initialization_frames = [0, 1, 2, 3] #First implementation is using only the two first frames
plot_tracked_points = True


vo_initialization_dict = initialize_visual_odometry(frames=initialization_frames, all_images_path=left_images,
                                                    K=camera_intrinsics, plot_tracked_points=plot_tracked_points)

R_iW = vo_initialization_dict['R_iW']
i_t_iW = vo_initialization_dict['i_t_iW']
matched_keypoints = vo_initialization_dict['matched_keypoints']
W_landmarks_of_keypoints = vo_initialization_dict['W_landmarks_of_keypoints']


# print("R_Wi:\n", R_Wi)
# print("W_t_Wi:\n", W_t_Wi)
print("R_iW\n", R_iW)
print("i_t_iW\n", i_t_iW)
w_t_Wi = - R_iW.T @ i_t_iW
print("w_t_Wi\n", w_t_Wi)

#TODO: Irgendwie flippen die vorzeichen zwischen den frames 0,1 und 0,1,2 immer noch sehr stark.


Frame 1: Tracked 526 / 526 points.
from previous num fratures: 526  to current num features: 526
Frame 2: Tracked 525 / 526 points.
from previous num fratures: 526  to current num features: 525
Frame 3: Tracked 525 / 525 points.
from previous num fratures: 525  to current num features: 525
Recovered Pose: 302 / 525 inliers after R,t estimation.
R_iW
 [[ 0.99993877  0.00403454 -0.01030391]
 [-0.00379189  0.99971756  0.02346104]
 [ 0.01039566 -0.02342053  0.99967165]]
i_t_iW
 [[-0.99601176]
 [-0.04296458]
 [-0.07819603]]
w_t_Wi
 [[0.99660076]
 [0.0451395 ]
 [0.06891553]]


# Part II
A continuous VO module that processes each frame Ii, estimates the current pose of the camera T i W C using the existing set of landmarks, and regularly triangulates new landmarks.

In [224]:
#Associate keypoints in the current frame to previously triangulated landmarks

In [225]:
#Based on this, estimate the current camera pose

In [226]:
# Regularly triangulate new landmarks using keypoints not associated to previously triangulated landmarks

invalid command name "133446401556096delayed_destroy"
    while executing
"133446401556096delayed_destroy"
    ("after" script)
invalid command name "133446651376640after"
    while executing
"133446651376640after"
    ("after" script)
invalid command name "133447728609472after"
    while executing
"133447728609472after"
    ("after" script)
invalid command name "133446681699840after"
    while executing
"133446681699840after"
    ("after" script)
