# Whole Pipeline


In [60]:
import os
import cv2
import numpy
from glob import glob

%load_ext autoreload
%autoreload 2

from va_functions.bootstrap import initialize_visual_odometry

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [61]:
# Data loader
from va_functions.data_loader import load_dataset

# Part I
An initialization module that extracts an initial set of 2D ↔ 3D correspondences from the first frames of the sequence and bootstraps the initial camera poses and landmarks.

In [62]:
dataset_id = 2 # This shoudl be dataset parking, i think the function descriptioj is wrong
left_images, right_images, camera_intrinsics = load_dataset(dataset_id)

In [63]:
print("left_images:", left_images[:3])

left_images: ['/home/simon/ETH/VAMR/va_final_prj/data/provided_data/parking/images/img_00000.png', '/home/simon/ETH/VAMR/va_final_prj/data/provided_data/parking/images/img_00001.png', '/home/simon/ETH/VAMR/va_final_prj/data/provided_data/parking/images/img_00002.png']


In [ ]:
# Extract initial set of 2D <-> 3D correspondences and bootstrap the Initial Camera Pose and landmarks

# Exampke usage:

initialization_frames = [0, 1, 2] #First implementation is using only the two first frames


vo_initialization_dict = initialize_visual_odometry(frames=initialization_frames, all_images_path=left_images,
                                                    K=camera_intrinsics)

R_Wi = vo_initialization_dict['R_Wi']
W_t_Wi = vo_initialization_dict['W_t_Wi']
matched_keypoints = vo_initialization_dict['matched_keypoints']
W_landmarks_of_keypoints = vo_initialization_dict['W_landmarks_of_keypoints']

print("R_Wi:\n", R_Wi)
print("W_t_Wi:\n", W_t_Wi)


K:
 [[331.37    0.    320.   ]
 [  0.    369.568 240.   ]
 [  0.      0.      1.   ]]
R_Wi:
 [[ 0.99943653 -0.03350504 -0.00201087]
 [ 0.0334754   0.99935095 -0.01330681]
 [ 0.00245541  0.013232    0.99990944]]
W_t_Wi:
 [[-0.38011436]
 [ 0.07434372]
 [-0.9219469 ]]


# Part II
A continuous VO module that processes each frame Ii, estimates the current pose of the camera T i W C using the existing set of landmarks, and regularly triangulates new landmarks.

In [65]:
#Associate keypoints in the current frame to previously triangulated landmarks

In [66]:
#Based on this, estimate the current camera pose

In [67]:
# Regularly triangulate new landmarks using keypoints not associated to previously triangulated landmarks