# Whole Pipeline


In [25]:
import os
import cv2
import numpy
from glob import glob



%load_ext autoreload
%autoreload 2


from va_functions.bootstrap import initialize_visual_odometry

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [26]:
# Data loader
from va_functions.data_loader import load_dataset

# Part I
An initialization module that extracts an initial set of 2D ↔ 3D correspondences from the first frames of the sequence and bootstraps the initial camera poses and landmarks.

In [27]:
dataset_id = 2 # This shoudl be dataset parking, i think the function descriptioj is wrong
left_images, right_images, camera_intrinsics = load_dataset(dataset_id)

In [28]:
print("left_images:", left_images[:3])

left_images: ['/home/simon/ETH/VAMR/va_final_prj/data/provided_data/parking/images/img_00000.png', '/home/simon/ETH/VAMR/va_final_prj/data/provided_data/parking/images/img_00001.png', '/home/simon/ETH/VAMR/va_final_prj/data/provided_data/parking/images/img_00002.png']


In [ ]:
# Extract initial set of 2D <-> 3D correspondences and bootstrap the Initial Camera Pose and landmarks

# Exampke usage:



initialization_frames = [0,1, 2, 3] #First implementation is using only the two first frames
plot_tracked_points = True


vo_initialization_dict = initialize_visual_odometry(frames=initialization_frames, all_images_path=left_images,
                                                    K=camera_intrinsics, plot_tracked_points=plot_tracked_points)

R_iW = vo_initialization_dict['R_iW']
i_t_iW = vo_initialization_dict['i_t_iW']
matched_keypoints = vo_initialization_dict['matched_keypoints']
W_landmarks_of_keypoints = vo_initialization_dict['W_landmarks_of_keypoints']


# print("R_Wi:\n", R_Wi)
# print("W_t_Wi:\n", W_t_Wi)
print("R_iW\n", R_iW)
print("i_t_iW\n", i_t_iW)
w_t_Wi = - R_iW.T @ i_t_iW
print("w_t_Wi\n", w_t_Wi)

#TODO: Irgendwie flippen die vorzeichen zwischen den frames 0,1 und 0,1,2 immer noch sehr stark.


R_iW
 [[ 9.30266514e-01 -3.66801691e-01 -7.79311015e-03]
 [ 3.66884363e-01  9.30040256e-01  2.05179728e-02]
 [-2.78120952e-04 -2.19463532e-02  9.99759111e-01]]
i_t_iW
 [[-0.03492285]
 [-0.07780357]
 [ 0.99635686]]
w_t_Wi
 [[ 0.06130958]
 [ 0.0814171 ]
 [-0.99479264]]


# Part II
A continuous VO module that processes each frame Ii, estimates the current pose of the camera T i W C using the existing set of landmarks, and regularly triangulates new landmarks.

In [30]:
#Associate keypoints in the current frame to previously triangulated landmarks

In [31]:
#Based on this, estimate the current camera pose

In [32]:
# Regularly triangulate new landmarks using keypoints not associated to previously triangulated landmarks